SET IDENTITY_INSERT [dbo].[tblAuthor] ON
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (1, N'Jane Smith               ', N'Jane Smith is an acclaimed author...', N'2022-01-01', 1, CAST(5.0 AS Decimal(18, 1)), 5000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (2, N'Robert Brown             ', N'Robert Brown writes thrilling novels...', N'2021-05-15', 0, CAST(4.0 AS Decimal(18, 1)), 7500)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (3, N'Emily White              ', N'Emily White is known for her romance novels...', N'2020-07-20', 1, CAST(5.0 AS Decimal(18, 1)), 12000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (4, N'Michael Green            ', N'Michael Green has a background in science fiction...', N'2019-09-10', 0, CAST(4.0 AS Decimal(18, 1)), 3000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (5, N'Sarah Black              ', N'Sarah Black is a prolific writer...', N'2018-03-22', 1, CAST(5.0 AS Decimal(18, 1)), 9000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (6, N'Chris Blue               ', N'Chris Blue writes captivating mysteries...', N'2017-11-11', 0, CAST(4.0 AS Decimal(18, 1)), 2000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (7, N'Linda Gold               ', N'Linda Gold is a celebrated author...', N'2016-06-06', 1, CAST(5.0 AS Decimal(18, 1)), 15000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (8, N'Paul Silver              ', N'Paul Silver is known for his historical fiction...', N'2015-04-14', 0, CAST(4.0 AS Decimal(18, 1)), 4000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (9, N'Alice Brown              ', N'Alice Brown writes insightful non-fiction...', N'2014-08-18', 1, CAST(5.0 AS Decimal(18, 1)), 10000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (10, N'Mark White               ', N'Mark White is an emerging author...', N'2013-12-01', 0, CAST(4.0 AS Decimal(18, 1)), 2500)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (11, N'Anna Grey                ', N'Anna Grey has published numerous bestsellers...', N'2012-07-23', 1, CAST(5.0 AS Decimal(18, 1)), 11000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (12, N'James Black              ', N'James Black focuses on crime fiction...', N'2011-10-30', 0, CAST(4.0 AS Decimal(18, 1)), 3500)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (13, N'Karen Pink               ', N'Karen Pink is a respected writer...', N'2010-05-17', 1, CAST(5.0 AS Decimal(18, 1)), 8000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (14, N'David Yellow             ', N'David Yellow writes engaging children’s books...', N'2009-03-12', 0, CAST(4.0 AS Decimal(18, 1)), 3000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (15, N'Mary Orange              ', N'Mary Orange is known for her fantasy novels...', N'2008-02-28', 1, CAST(5.0 AS Decimal(18, 1)), 14000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (16, N'John Blue                ', N'John Blue has a knack for storytelling...', N'2007-09-14', 0, CAST(4.0 AS Decimal(18, 1)), 4500)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (17, N'Laura Purple             ', N'Laura Purple has written numerous award-winning books...', N'2006-12-19', 1, CAST(5.0 AS Decimal(18, 1)), 16000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (18, N'Steve Red                ', N'Steve Red specializes in thrillers...', N'2005-07-05', 0, CAST(4.0 AS Decimal(18, 1)), 6000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (19, N'Nancy Violet             ', N'Nancy Violet is an expert in suspense writing...', N'2004-11-27', 1, CAST(5.0 AS Decimal(18, 1)), 9500)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (20, N'Alex Green               ', N'Alex Green is a novelist known for contemporary fiction...', N'2003-04-15', 0, CAST(4.0 AS Decimal(18, 1)), 3500)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (21, N'John Doe                 ', N'John Doe is a famous author...', N'2023-01-01', 1, CAST(5.0 AS Decimal(18, 1)), 10000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (34, N'yyy yyy                  ', N'Updated Biography', N'2023-06-05', 0, CAST(3.5 AS Decimal(18, 1)), 1000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (35, N'yyy yyy                  ', N'Test Biography', N'2024-06-05', 1, CAST(4.5 AS Decimal(18, 1)), 10000)
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (22, N'J.K. Rowling', N'J.K. Rowling is a British author, best known for the Harry Potter series.', N'1997-06-26', 1, CAST(4.8 AS Decimal(18, 2)), 500000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (23, N'Stephen King', N'Stephen King is an American author of horror, supernatural fiction, suspense, and fantasy novels.', N'1974-04-05', 1, CAST(4.5 AS Decimal(18, 2)), 350000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (24, N'George R.R. Martin', N'George R.R. Martin is an American novelist and short-story writer, known for the A Song of Ice and Fire series.', N'1996-08-06', 1, CAST(4.7 AS Decimal(18, 2)), 90000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (25, N'Agatha Christie', N'Agatha Christie was an English writer known for her 66 detective novels and 14 short story collections.', N'1920-10-01', 1, CAST(4.6 AS Decimal(18, 2)), 2000000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (26, N'J.R.R. Tolkien', N'J.R.R. Tolkien was an English writer, poet, philologist, and academic, best known for The Hobbit and The Lord of the Rings.', N'1937-09-21', 1, CAST(4.9 AS Decimal(18, 2)), 300000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (27, N'Dan Brown', N'Dan Brown is an American author best known for his thriller novels, including the Robert Langdon series.', N'2000-03-28', 1, CAST(4.3 AS Decimal(18, 2)), 200000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (28, N'Haruki Murakami', N'Haruki Murakami is a Japanese writer known for his blend of pop culture, fantasy, and a magical realist style.', N'1987-10-01', 1, CAST(4.4 AS Decimal(18, 2)), 150000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (29, N'Isaac Asimov', N'Isaac Asimov was an American writer and professor of biochemistry, known for his works of science fiction and popular science.', N'1950-01-02', 1, CAST(4.8 AS Decimal(18, 2)), 70000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (30, N'Jane Austen', N'Jane Austen was an English novelist known for her six major novels, including Pride and Prejudice and Sense and Sensibility.', N'1811-10-30', 1, CAST(4.7 AS Decimal(18, 2)), 200000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (31, N'Ernest Hemingway', N'Ernest Hemingway was an American novelist, short-story writer, and journalist, known for his economical and understated style.', N'1926-10-01', 1, CAST(4.5 AS Decimal(18, 2)), 80000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (32, N'F. Scott Fitzgerald', N'F. Scott Fitzgerald was an American novelist, best known for his novel The Great Gatsby.', N'1920-10-01', 1, CAST(4.6 AS Decimal(18, 2)), 40000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (33, N'Mark Twain', N'Mark Twain was an American writer, humorist, entrepreneur, publisher, and lecturer, known for The Adventures of Tom Sawyer and The Adventures of Huckleberry Finn.', N'1876-01-01', 1, CAST(4.7 AS Decimal(18, 2)), 100000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (34, N'Charles Dickens', N'Charles Dickens was an English writer and social critic, known for his novels such as A Christmas Carol, Oliver Twist, and Great Expectations.', N'1837-01-01', 1, CAST(4.8 AS Decimal(18, 2)), 300000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (35, N'Leo Tolstoy', N'Leo Tolstoy was a Russian writer who is regarded as one of the greatest authors of all time, known for War and Peace and Anna Karenina.', N'1869-01-01', 1, CAST(4.7 AS Decimal(18, 2)), 80000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (36, N'Arthur Conan Doyle', N'Arthur Conan Doyle was a British writer best known for his detective fiction featuring the character Sherlock Holmes.', N'1887-01-01', 1, CAST(4.8 AS Decimal(18, 2)), 90000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (37, N'Mary Shelley', N'Mary Shelley was an English novelist who wrote the Gothic novel Frankenstein; or, The Modern Prometheus.', N'1818-01-01', 1, CAST(4.6 AS Decimal(18, 2)), 50000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (38, N'George Orwell', N'George Orwell was an English novelist, essayist, journalist, and critic, known for his novels Animal Farm and Nineteen Eighty-Four.', N'1945-01-01', 1, CAST(4.9 AS Decimal(18, 2)), 250000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (39, N'Virginia Woolf', N'Virginia Woolf was an English writer, considered one of the most important modernist 20th-century authors.', N'1925-01-01', 1, CAST(4.4 AS Decimal(18, 2)), 60000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (40, N'Gabriel Garcia Marquez', N'Gabriel Garcia Marquez was a Colombian novelist, short-story writer, screenwriter, and journalist, known for One Hundred Years of Solitude.', N'1967-01-01', 1, CAST(4.8 AS Decimal(18, 2)), 80000000);
INSERT INTO [dbo].[tblAuthor] ([AuthorId], [AuthorName], [AuthorBiography], [DateJoined], [IsBestseller], [AverageRating], [TotalBooksSold]) VALUES (41, N'Margaret Atwood', N'Margaret Atwood is a Canadian poet, novelist, literary critic, essayist, teacher, environmental activist, and inventor.', N'1985-01-01', 1, CAST(4.7 AS Decimal(18, 2)), 30000000);
SET IDENTITY_INSERT [dbo].[tblAuthor] OFF
